name: Kind Cluster E2E tests - Namespaced

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
        with:
          version: v0.13.0
          kubectl_version: v1.24.0
          cluster_name: kinder
          config: ./hack/kind-config.yaml
      - uses: actions/setup-go@v3 # default version of go is 1.10
        with:
          go-version: "1.17.6"
      - name: Install Carvel Tools
        run: ./hack/install-deps.sh
      # Run benchmark with `go test -bench` and stores the output to a file
      - name: Install kc and run e2e tests on kind
        run: |
          set -e -x
          kubectl version --short
          
          ytt -v reconcile_namespace=kappctrl-test -v reconcile_scope=namespace -v namespace=kappctrl-test -f config/ | kbld -f- > kbld.out 2> kbldmeta.out
          cat kbldmeta.out | tail -n 1 | sed 's/.*final: kapp-controller -> \(.*\)$/\1/p'  | tail -n 1 | xargs kind load docker-image --name kinder
          kubectl apply -f kbld.out
          ytt -v reconcile_scope=cluster -v namespace=kapp-controller  -f config/ | kbld -f- | kubectl apply -f-
          
          export KAPPCTRL_E2E_SECRETGEN_CONTROLLER=true
          source ./hack/secretgen-controller.sh
          deploy_secretgen-controller
          mkdir tmp
          KAPPCTRL_E2E_NAMESPACE=kappctrl-test KAPPCTRL_E2E_SKIP_IN_NS_SUPPORT=true eval './hack/test-e2e.sh'
